### ISSUE TITLE
Search not finding all results

### ISSUE THREAD

**Issue by adamfortuna** [orientation/orientation#150] opened 2015-08-03 14:49 UTC
Looks like search might not be giving back all results. I'm searching for a keyword that's in the content of an article and also in it's keywords, but doesn't seem to show up.

**Comment by olivierlacan** [comment] 2015-08-03 18:50
By keyword you mean tags? We don't search these yet. 

I've noticed anomalies like this before. Can you post the entire article content in a private gist and send it to me so I can try to isolate that bug in a regression test?

**Comment by adamfortuna** [comment] 2015-08-03 18:59
I sent you a link to the page over Slack if that works. :) If you need anything else let me know. In this case it's wasn't specific to tags. The term I was searching for is in the body in a number of ways (headers, in code, in links and in regular text) as well as being a tag -- but didn't seem to show up in a search.

**Comment by olivierlacan** [comment] 2015-08-03 19:52
I'm curious if @craigkerstiens can help with this one. These are the indices we have on `articles.content` and `articles.title`:

```SQL
CREATE INDEX articles_content ON articles USING gin (to_tsvector('english'::regconfig, content));
CREATE INDEX articles_title ON articles USING gin (to_tsvector('english'::regconfig, (title)::text));
```

Not sure why they're different to be honest. I need to read up more because the difference may explain why articles with multiple counts of one unique word in their content don't show up in results.

**Comment by olivierlacan** [comment] 2015-09-19 21:39
I'm going to close this for now since I've [recently made article search focus exclusively on titles](https://github.com/orientation/orientation/blob/master/NEWS.md#advanced-search-vs-fuzzy-search).

I know it's not a fix per se but I can't think of an easier way right now to make this better so I'm going to close this.

**Closed by olivierlacan** 2015-09-19 21:39 UTC
